# Generated by Django 4.1.3 on 2022-12-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, null=True)),
                ('success', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('classes', models.IntegerField(null=True)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('request_timestamp', models.PositiveIntegerField(null=True)),
                ('response_timestamp', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
